Readme:
If have problem in clone the repo, please clear the runtime and re-run the cell.

In [0]:
from sklearn import linear_model
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import csv
!git clone https://github.com/lovethatcat/DataMining.git


In [0]:
def loadCSVfile2():
    tmp = np.loadtxt("./DataMining/training.csv", dtype=np.str, delimiter=",")
    X_train = tmp[1:14700,1:].astype(np.float)
    Y_train = tmp[1:14700,0].astype(np.float)
    X_test  = tmp[14700:21000,1:].astype(np.float)
    Y_test = tmp[14700:21000,0].astype(np.float)
    return X_train, Y_train,X_test,Y_test 


In [0]:
def loadtest():
    tmp = np.loadtxt("./DataMining/testing.csv", dtype=np.str, delimiter=",")
    data = tmp[1:,0:].astype(np.float)
    return data 

In [0]:
X_train, Y_train,X_test,Y_test =loadCSVfile2()


# Neural network

In [7]:
from sklearn.neural_network import MLPClassifier
from sklearn import metrics
clf = MLPClassifier(alpha=1e-5,hidden_layer_sizes=(200,50),max_iter=6000)
clf.fit(X_train,Y_train)
clf.score(X_test, Y_test)
#print(score)

0.9415873015873016

# Random Forest

In [8]:
from sklearn.ensemble import RandomForestClassifier
RFC = RandomForestClassifier(max_depth=10, random_state=0)
RFC.fit(X_train,Y_train)
Y_predict = RFC.predict(X_test)
print("Accuracy:", metrics.accuracy_score(Y_test, Y_predict))

Accuracy: 0.9371428571428572


# print test label

In [9]:
TEST=loadtest()
Y_predictMLP = clf.predict(TEST)
print(Y_predictMLP)

[1. 0. 1. ... 4. 6. 0.]


In [11]:
Y_predictRFC = RFC.predict(TEST)
print(Y_predictRFC)

[1. 0. 1. ... 4. 6. 0.]


# Save the model

In [14]:
import os
from google.colab import drive
drive.mount('/content/drive')

path = "/content/drive/My Drive"

os.chdir(path)
os.listdir(path)
 

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


['Getting started.pdf',
 'Colab Notebooks',
 'data.py',
 'training.py',
 'dataset.npy',
 'drug.txt',
 'interactionmetrix.txt',
 'target.txt',
 'datasety.npy',
 'final presentation - Bar chart 1.gsheet',
 'Untitled spreadsheet.gsheet',
 'sharetosis',
 'lena.JPG']

In [16]:
from sklearn.externals import joblib
joblib.dump(clf, '/content/drive/My Drive/MLP.pkl') 
joblib.dump(RFC, '/content/drive/My Drive/RFC.pkl')

['/content/drive/My Drive/RFC.pkl']

In [0]:
np.savetxt("/content/drive/My Drive/Y_predictMLP.csv", Y_predictMLP, delimiter=',')
np.savetxt("/content/drive/My Drive/Y_predictRFC.csv", Y_predictRFC, delimiter=',')

# FOR TA to test 

1. Please copy this code to **IDE** and change the following Comment line
2. You can also directly check the label file: **Y_predictMLP.csv** and **Y_predictRFC.csv** which are generated by testing.csv data

In [22]:
from sklearn.externals import joblib
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
import numpy as np
import csv

def loadtest():
    tmp = np.loadtxt("./DataMining/testing.csv", dtype=np.str, delimiter=",")           # change to the local path by       tmp = np.loadtxt("testing.csv", dtype=np.str, delimiter=",")
    data = tmp[1:,0:].astype(np.float)
    return data
def loadtruelabel():
    truelabel=np.loadtxt("please in put the path of true label", dtype=np.str, delimiter=",") # change to the local path to load the true label and please make sure the foramt of label data is right.
    return truelabel

theMLP = joblib.load('./DataMining/MLP.pkl')                               # change to the local path by        theMLP = joblib.load('MLP.pkl')
theRFC = joblib.load('./DataMining/RFC.pkl')                               # change to the local path by        theRFC = joblib.load('RFC.pkl')
TEST=loadtest()
MLP_label = theMLP.predict(TEST)
RFC_Label = theRFC.predict(TEST)
print(MLP_label)
print(RFC_Label)
#Y_true=loadtruelabel()                                           #######  DELETE the "#" to show final accuracy
#print("Accuracy of MLP:", metrics.accuracy_score(Y_true, MLP_label))                  #######  DELETE the "#" to show final accuracy
#print("Accuracy of RFCP:", metrics.accuracy_score(Y_true, RFC_Label))                  #######  DELETE the "#" to show final accuracy

[1. 0. 1. ... 4. 6. 0.]
[1. 0. 1. ... 4. 6. 0.]
